'use strict';

const PROJECTS = [
  {
    id: "craftgame",
    title: "Craft Game",
    desc: "Jeu de craft inspiré d'Infinite Craft — fusionne des éléments pour en découvrir de nouveaux, des quarks jusqu'à l'univers.",
    emoji: "⚗️",
    tags: ["jeu"],
    github: "https://github.com/kevinraphael95/craftgame",
    site: "https://kevinraphael95.github.io/craftgame/index.html",
    lang: "JS",
    color: "purple",
  },
  {
    id: "tupreferes",
    title: "Tu Préfères",
    desc: "Jeu — choisir entre deux pages Wikipedia aléatoires. Laquelle est la meilleure ?",
    emoji: "🎲",
    tags: ["jeu"],
    github: "https://github.com/kevinraphael95/tupreferes",
    site: "https://kevinraphael95.github.io/tupreferes/wiki-prefer.html",
    lang: "JS",
    color: "teal",
  },
  {
    id: "drawword",
    title: "DrawWord",
    desc: "Jeu / test — dessiner avec des mots une page aléatoire de Wikipedia. Art génératif textuel.",
    emoji: "🖊️",
    tags: ["jeu"],
    github: "https://github.com/kevinraphael95/DRAWWORD",
    site: "https://kevinraphael95.github.io/DRAWWORD/index.html",
    lang: "JS",
    color: "amber",
  },
  {
    id: "wikitcg",
    title: "WikiTCG",
    desc: "Génère des cartes Magic et Yu-Gi-Oh! à partir d'un article Wikipedia aléatoire.",
    emoji: "🌀",
    tags: ["jeu", "tcg"],
    github: "https://github.com/kevinraphael95/wikitcg",
    site: "https://kevinraphael95.github.io/wikitcg/wikitcg.html",
    lang: "JS",
    color: "blue",
  },
  {
    id: "kevinscale",
    title: "Kévinscale",
    desc: "Version custom de PolitiScale.",
    emoji: "📊",
    tags: ["quizz"],
    github: "https://github.com/kevinraphael95/kevinscale",
    site: "https://kevinraphael95.github.io/kevinscale/",
    lang: "JS",
    color: "coral",
  },
  {
    id: "kisuke",
    title: "Bot Discord Kisuke Urahara",
    desc: "Bot Discord inspiré de Bleach — personnalité et commandes dans l'univers de Kisuke Urahara.",
    emoji: "🪭",
    tags: ["bot"],
    github: "https://github.com/kevinraphael95/discord_bot_kisuke_urahara",
    site: "https://kevinraphael95.github.io/discord_bot_kisuke_urahara/",
    lang: "Python",
    color: "teal",
  },
  {
    id: "atem",
    title: "Bot Discord Atem / Yu-Gi-Oh!",
    desc: "Bot Discord inspiré de Yu-Gi-Oh! — commandes, duels et références à l'univers du manga.",
    emoji: "👁️",
    tags: ["bot"],
    github: "https://github.com/kevinraphael95/atem_discord_bot",
    site: "https://kevinraphael95.github.io/atem_discord_bot/index.html",
    lang: "Python",
    color: "amber",
  },
  {
    id: "mhfz",
    title: "Bot Monster Hunter",
    desc: "Bot Discord Monster Hunter Frontier Z — infos, commandes et références à l'univers MH.",
    emoji: "⚔️",
    tags: ["bot"],
    github: "https://github.com/kevinraphael95/mhfz",
    site: "https://kevinraphael95.github.io/mhfz/",
    lang: "Python",
    color: "green",
  },
  {
    id: "vaact",
    title: "Cartes YGO — VAACT",
    desc: "Cartes Yu-Gi-Oh! custom créées pour le projet VAACT. Fan-made, design soigné.",
    emoji: "🃏",
    tags: ["tcg"],
    github: "https://github.com/kevinraphael95/vaact_custom_ygo",
    site: null,
    lang: "Assets",
    color: "purple",
  },
  {
    id: "darksouls",
    title: "Cartes YGO — Dark Souls",
    desc: "Cartes Yu-Gi-Oh! custom à l'univers Dark Souls. Fan-made crossover.",
    emoji: "🔥",
    tags: ["tcg"],
    github: "https://github.com/kevinraphael95/darksoulsygo",
    site: null,
    lang: "Assets",
    color: "red",
  },
];
