'use strict';

const PROJECTS = [
  {
    id: "atem",
    title: "Atem",
    subtitle: "Bot discord Yu-Gi-Oh!",
    desc: "Bot Discord inspiré de Yu-Gi-Oh!",
    emoji: "👁️",
    img: "assets/images/atem.png",
    tags: ["bot"],
    github: "https://github.com/kevinraphael95/atem_discord_bot",
    site: "https://kevinraphael95.github.io/atem_discord_bot/",
    status: "alpha",
    palette: ["#1a0a00", "#f5c842", "#8b0000"],
  },
  {
    id: "captcha",
    title: "Captcha",
    subtitle: "I'm not a robot",
    desc: "Un Captcha pour prouver que tu es humain, mais l'IA du Captcha devient de plus en plus bizarre.",
    emoji: "🗿",
    img: "assets/images/captcha.png",
    tags: ["jeu"],
    github: "https://github.com/kevinraphael95/captcha",
    site: "https://kevinraphael95.github.io/captcha/",
    status: "proof of concept",
    palette: ["#f0f0f0", "#333", "#888"],
  },
  {
    id: "craftgame",
    title: "Craft Game",
    subtitle: "Fusionne des trucs",
    desc: "Recréer l'univers et tout dans l'univers à partir des particules élémentaires.",
    emoji: "⚗️",
    img: "assets/images/craftgame.png",
    tags: ["jeu"],
    github: "https://github.com/kevinraphael95/craftgame",
    site: "https://kevinraphael95.github.io/craftgame/",
    status: "proof of concept",
    palette: ["#1a1a2e", "#7c3aed", "#a78bfa"],
  },
  {
    id: "darksouls",
    title: "Dark Souls × YGO",
    subtitle: "Cartes custom",
    desc: "Cartes Yu-Gi-Oh! custom dans l'univers Dark Souls.",
    emoji: "🔥",
    img: "assets/images/darksoulsygo.jpg",
    tags: ["tcg"],
    github: "https://github.com/kevinraphael95/darksoulsygo",
    site: null,
    status: "abandonné",
    palette: ["#1c1007", "#e07b39", "#3d2b0a"],
  },
  {
    id: "drawword",
    title: "DrawWord",
    subtitle: "Dessine avec Wikipedia",
    desc: "Un mélange entre paint, word et wikipédia.",
    emoji: "🖊️",
    img: "assets/images/drawword.png",
    tags: ["jeu"],
    github: "https://github.com/kevinraphael95/DRAWWORD",
    site: "https://kevinraphael95.github.io/DRAWWORD/",
    status: "proof of concept",
    palette: ["#fff8ee", "#d97706", "#fef3c7"],
  },
  {
    id: "foresttest",
    title: "Forêt",
    subtitle: "C'est une forêt",
    desc: "Une forêt. Tu te balades. C'est vert.",
    emoji: "🌳",
    img: "assets/images/foret.png",
    tags: ["jeu"],
    github: "https://github.com/kevinraphael95/forest",
    site: "https://kevinraphael95.github.io/forest/",
    status: "minimum vital product",
    palette: ["#052e16", "#16a34a", "#bbf7d0"],
  },
  {
    id: "jardin",
    title: "Jardin",
    subtitle: "Des fleurs",
    desc: "Un jardin avec des fleurs.",
    emoji: "🌼",
    img: "assets/images/jardin.png",
    tags: ["jeu"],
    github: "https://github.com/kevinraphael95/jardin",
    site: "https://kevinraphael95.github.io/jardin/",
    status: "proof of concept",
    palette: ["#fdf4ff", "#d946ef", "#fce7f3"],
  },
  {
    id: "kevinscale",
    title: "Kévinscale",
    subtitle: "Quiz politique",
    desc: "Version custom de PolitiScale — découvre à quel point tu es Kévin.",
    emoji: "📊",
    img: "assets/images/kevinscale.png",
    tags: ["quizz"],
    github: "https://github.com/kevinraphael95/kevinscale",
    site: "https://kevinraphael95.github.io/kevinscale/",
    status: "beta",
    palette: ["#1e1b4b", "#6366f1", "#c7d2fe"],
  },
  {
    id: "kisuke",
    title: "Kisuke Urahara",
    subtitle: "Bot discord Bleach",
    desc: "Bot Discord inspiré de Bleach, commandes fun, basées sur Bleach, minijeu de reiatsu + Bleach Character Guesser.",
    emoji: "🪭",
    img: "assets/images/kisuke.jpg",
    tags: ["bot"],
    github: "https://github.com/kevinraphael95/discord_bot_kisuke_urahara",
    site: "https://kevinraphael95.github.io/discord_bot_kisuke_urahara/",
    status: "alpha",
    palette: ["#0f2027", "#10b981", "#d1fae5"],
  },
  {
    id: "mhfz",
    title: "Monster Hunter",
    subtitle: "Bot Discord MHFZ",
    desc: "Bot Discord utilitaire pour Monster Hunter Frontier Z + Monster Guesser.",
    emoji: "⚔️",
    img: "assets/images/mhfz.jpg",
    tags: ["bot"],
    github: "https://github.com/kevinraphael95/mhfz",
    site: "https://kevinraphael95.github.io/mhfz/",
    status: "proof of concept",
    palette: ["#0f1923", "#ef4444", "#fca5a5"],
  },
  {
    id: "notsteam",
    title: "NotSteam",
    subtitle: "C'est pas Steam",
    desc: "Une bibliothèque de jeux. Pas Steam. Vraiment pas. Collection de ROMS gratuites prises partout sur internet.",
    emoji: "🕹️",
    img: "assets/images/notsteam.png",
    tags: ["jeu"],
    github: "https://github.com/kevinraphael95/notsteam",
    site: "https://kevinraphael95.github.io/notsteam/",
    status: "proof of concept",
    palette: ["#1b2838", "#66c0f4", "#c6d4df"],
  },
  {
    id: "proftolio",
    title: "Proftolio",
    subtitle: "Proftolio",
    desc: "Liste de tous les trucs. Un portfolio. Proftolio.",
    emoji: "📋",
    img: "assets/images/proftolio.png",
    tags: ["jeu"],
    github: "https://github.com/kevinraphael95/proftolio",
    site: "https://kevinraphael95.github.io/proftolio/",
    status: "alpha",
    palette: ["#18181b", "#a855f7", "#e9d5ff"],
  },
  {
    id: "smashcar",
    title: "SmashCar",
    subtitle: "SmashCar",
    desc: "SmashCar.",
    emoji: "📋",
    img: "assets/images/smashcar.png",
    tags: ["jeu"],
    github: "https://github.com/kevinraphael95/smashcar",
    site: "https://kevinraphael95.github.io/smashcar/",
    status: "proof of concept",
    palette: ["#18181b", "#a855f7", "#e9d5ff"],
  },
  {
    id: "bleachquiz",
    title: "The ImpossiBLEACH Quiz",
    subtitle: "The ImpossiBLEACH Quiz",
    desc: "The ImpossiBLEACH Quiz",
    emoji: "🎲",
    tags: ["jeu", "quiz"],
    github: "https://github.com/kevinraphael95/bleachquiz",
    site: "https://kevinraphael95.github.io/bleachquiz/",
    status: "proof of concept",
    palette: ["#0f172a", "#06b6d4", "#cffafe"],
  },
  {
    id: "tupreferes",
    title: "Tu Préfères",
    subtitle: "Wikipedia battle",
    desc: "Choisis entre deux pages Wikipedia aléatoires. Laquelle gagne ?",
    emoji: "🎲",
    tags: ["jeu"],
    github: "https://github.com/kevinraphael95/tupreferes",
    site: "https://kevinraphael95.github.io/tupreferes/",
    status: "proof of concept",
    palette: ["#0f172a", "#06b6d4", "#cffafe"],
  },
  {
    id: "vaact",
    title: "VAACT × YGO",
    subtitle: "Cartes custom",
    desc: "Cartes Yu-Gi-Oh! custom VAACT.",
    emoji: "🃏",
    tags: ["tcg"],
    github: "https://github.com/kevinraphael95/vaact_custom_ygo",
    site: null,
    status: "abandonné",
    palette: ["#1a1a1a", "#8b5cf6", "#ede9fe"],
  },
  {
    id: "whosthatpokemon",
    title: "Who's that Pokémon?",
    subtitle: "Devine le Pokémon",
    desc: "Who's that Pokemon ?",
    emoji: "👁️",
    img: "assets/images/wtp.jpg",
    tags: ["jeu"],
    github: "https://github.com/kevinraphael95/whosthatpokemon",
    site: "https://kevinraphael95.github.io/whosthatpokemon/",
    status: "beta",
    palette: ["#ffcb05", "#3b4cca", "#cc0000"],
  },
  {
    id: "wikigames",
    title: "Wiki Games",
    subtitle: "Wikipedia games",
    desc: "Wikipedia Games !",
    emoji: "🌀",
    tags: ["jeu"],
    github: "https://github.com/kevinraphael95/wikigames",
    site: "https://kevinraphael95.github.io/wikigames/",
    status: "proof of concept",
    palette: ["#0a0a0a", "#3b82f6", "#bfdbfe"],
  },
  {
    id: "wikitcg",
    title: "WikiTCG",
    subtitle: "Wikipedia → Cartes",
    desc: "Transforme un article Wikipedia aléatoire en carte Magic et Yu-Gi-Oh!",
    emoji: "🌀",
    tags: ["jeu", "tcg"],
    github: "https://github.com/kevinraphael95/wikitcg",
    site: "https://kevinraphael95.github.io/wikitcg/",
    status: "proof of concept",
    palette: ["#0a0a0a", "#3b82f6", "#bfdbfe"],
  },
];
